apiVersion: apps/v1
kind: Deployment
metadata:
  name: akhq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akhq
  template:
    metadata:
      labels:
        app: akhq
    spec:
      containers:
      - name: akhq
        image: tchiotludo/akhq:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: AKHQ_CONFIGURATION
          value: |
            akhq:
              connections:
                docker-kafka-server:
                  properties:
                    bootstrap.servers: "kafka:29092"
