apiVersion: v1
kind: Service
metadata:
  name: registration-mongodb
spec:
  selector:
    app: registration-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
