apiVersion: v1
kind: ConfigMap
metadata:
  name: registration-service-config
data:
  SPRING_APPLICATION_NAME: registration-service
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
  SPRING_DATA_MONGODB_URI: mongodb://admin:password123@registration-mongodb:27017/registration_db?authSource=admin
