apiVersion: v1
kind: ConfigMap
metadata:
  name: audit-service-config
data:
  SPRING_APPLICATION_NAME: audit-service
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  AUDIT_KAFKA_TOPICS_AUDIT_EVENTS: audit.events
  AUDIT_KAFKA_TOPICS_API_GATEWAY_EVENTS: audit.api-gateway
  AUDIT_KAFKA_TOPICS_AUTHENTICATION_EVENTS: audit.authentication
  AUDIT_KAFKA_CONSUMER_GROUP_ID: audit-service-group
