apiVersion: v1
kind: ConfigMap
metadata:
  name: employee-service-config
data:
  SPRING_APPLICATION_NAME: employee-service
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
