apiVersion: v1
kind: ConfigMap
metadata:
  name: employee-mysql-initdb-config
data:
  init.sql: |
    CREATE USER 'user'@'%' IDENTIFIED BY 'password';
    GRANT ALL PRIVILEGES ON employee_db.* TO 'user'@'%';
    FLUSH PRIVILEGES;
